### ISSUE TITLE
Having invalid Discord bot URL causes errors.

### ISSUE THREAD

**Issue by axewater** [axewater/sharewarez#117]
This error should be handled more gracefully, we need to catch a few cases of possible errors.
(server unreachable, host name unresolvable, .. ?)

Failed to process game Fallout: HTTPConnectionPool(host='www.discordwebhookurl.com', port=80): Max retries exceeded with url: /url/index.htm?wait=True (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001E921A23510>: Failed to resolve 'www.discordwebhookurl.com' ([Errno 11001] getaddrinfo failed)"))
Exception in thread Thread-38 (start_scan):
Traceback (most recent call last):
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\urllib3\connection.py", line 200, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\urllib3\connection.py", line 388, in request
    self.endheaders()
  File "C:\Python311\Lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python311\Lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Python311\Lib\http\client.py", line 976, in send
    self.connect()
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\urllib3\connection.py", line 236, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\urllib3\connection.py", line 207, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x000001E921A23510>: Failed to resolve 'www.discordwebhookurl.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.discordwebhookurl.com', port=80): Max retries exceeded with url: /url/index.htm?wait=True (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001E921A23510>: Failed to resolve 'www.discordwebhookurl.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\scripts\sharewarez\modules\utilities.py", line 1087, in scan_and_add_games
    success = process_game_with_fallback(game_name, full_disk_path, scan_job_entry.id, library_uuid)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\scripts\sharewarez\modules\utilities.py", line 1142, in process_game_with_fallback
    if not try_add_game(game_name, full_disk_path, scan_job_id, library_uuid=library_uuid, check_exists=False):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\scripts\sharewarez\modules\utilities.py", line 1175, in try_add_game
    game = retrieve_and_save_game(game_name, full_disk_path, scan_job_id, library_uuid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\scripts\sharewarez\modules\utilities.py", line 410, in retrieve_and_save_game
    new_game = create_game_instance(game_data=response_json[0], full_disk_path=full_disk_path, folder_size_bytes=folder_size_bytes, library_uuid=library.uuid)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\scripts\sharewarez\modules\utilities.py", line 211, in create_game_instance
    discord_webhook(new_game.uuid)
  File "c:\scripts\sharewarez\modules\utilities.py", line 1407, in discord_webhook
    response = webhook.execute()
               ^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\discord_webhook\webhook.py", line 444, in execute
    response = self.api_post_request()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\discord_webhook\webhook.py", line 388, in api_post_request
    return requests.post(
           ^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.discordwebhookurl.com', port=80): Max retries exceeded with url: /url/index.htm?wait=True (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001E921A23510>: Failed to resolve 'www.discordwebhookurl.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(512)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\flask\ctx.py", line 184, in wrapper
    return ctx.app.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\scripts\sharewarez\modules\routes.py", line 1124, in start_scan
    scan_and_add_games(full_path, scan_mode, library_uuid)
  File "c:\scripts\sharewarez\modules\utilities.py", line 1109, in scan_and_add_games
    db.session.commit()
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4296, in flush
    self._flush(objects)
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4431, in _flush
    with util.safe_reraise():
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4392, in _flush
    flush_context.execute()
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1421, in execute
    return meth(
           ^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1849, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "C:\scripts\sharewarez\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(512)

[SQL: UPDATE scan_jobs SET error_message=%(error_message)s, folders_failed=%(folders_failed)s WHERE scan_jobs.id = %(scan_jobs_id)s]
[parameters: {'error_message': ' Failed to process Doom: HTTPConnectionPool(host=\'www.discordwebhookurl.com\', port=80): Max retries exceeded with url: /url/index.htm?wait=True (Ca ... (367 characters truncated) ... lib3.connection.HTTPConnection object at 0x000001E921A23510>: Failed to resolve \'www.discordwebhookurl.com\' ([Errno 11001] getaddrinfo failed)")); ', 'folders_failed': 2, 'scan_jobs_id': '6a897a1d-26a7-4c20-940c-617c9c6d422a'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)

**Comment by Bovive** [comment]
What were you using as a webhook URL? I put in an incorrect URL and this was my console response:

```Webhook status code 401: {"message": "Invalid Webhook Token", "code": 50027}```

**Comment by Bovive** [comment]
Tested again this time with an incorrectly formatted URL and received a different response.

```
Failed to process game Just Crow Things: No connection adapters were found for 'httpsss://discord.com?wait=True'
Game already exists in database: Pinball Fx3 at D:\Test Games\PC\Pinball FX3
Failed to process game Pinball Fx3: 'UPDATE_FOLDER_NAME'
Exception in thread Thread-525 (start_scan):
Traceback (most recent call last):
  File "D:\Development\SharewareZ\sharewarez\modules\utilities.py", line 1092, in scan_and_add_games
    updates_folder = os.path.join(full_disk_path, current_app.config['UPDATE_FOLDER_NAME'])
                                                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'UPDATE_FOLDER_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(512)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\ctx.py", line 184, in wrapper
    return ctx.app.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Development\SharewareZ\sharewarez\modules\routes.py", line 1124, in start_scan
    scan_and_add_games(full_path, scan_mode, library_uuid)
  File "D:\Development\SharewareZ\sharewarez\modules\utilities.py", line 1109, in scan_and_add_games
    db.session.commit()
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\session.py", line 4352, in flush
    self._flush(objects)
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\session.py", line 4487, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\session.py", line 4448, in _flush
    flush_context.execute()
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\orm\persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(512)

[SQL: UPDATE scan_jobs SET error_message=%(error_message)s, folders_success=%(folders_success)s, folders_failed=%(folders_failed)s WHERE scan_jobs.id = %(scan_jobs_id)s]
[parameters: {'error_message': " Failed to process 9 Bit Armies: 'UPDATE_FOLDER_NAME';  Failed to process Above Snakes: No connection adapters were found for 'httpsss://discord.com/ ... (231 characters truncated) ... ?wait=True';  Failed to process Pinball Fx3: 'UPDATE_FOLDER_NAME'; ", 'folders_success': 2, 'folders_failed': 4, 'scan_jobs_id': '134b0244-560b-4a1b-b44c-db712e7fe6e4'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
```

The error also appears in the Scan Jobs Management "Error" column:

```
'UPDATE_FOLDER_NAME'; Failed to process Above Snakes: No connection adapters were found for 'httpsss://discord.com?wait=True'; Failed to process Just Crow Things: No connection adapters were found for 'httpsss://discord.com/api/webhooks/1285743784390299783/9J_MF5298-nt1tpOFCXTBDUXBbcioLBdCFGJuxEqPXnWf9AU_7Haw2PNNF8LKJe1Ys-Y?wait=True';
```

It looks like the Discord module is handling the error correctly. This has something to do with ```UPDATE_FOLDER_NAME``` but I do not understand why.

**Comment by Bovive** [comment]
Additionally games that error do not retrieve all their meta data:

![Screenshot_28-10-2024_191242_127 0 0 1](https://github.com/user-attachments/assets/c66df282-4103-47c4-a71f-9609da4c50e2)

**Comment by Bovive** [comment]
Ok figured it out. The discord function was running after the exceptions in create_game_instance. I'll put in a PR.
