### ISSUE TITLE
Cannot Edit Games

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#52]
I thought I broke this, but I started a whole new database and did a new pull from the main repo. When I try to edit the IGDB match for a game I receive this error when I click "Save".

```
NameError
NameError: name 'get_folder_size_in_bytes' is not defined

Traceback (most recent call last)
File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 2213, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 2193, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\bturn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask_login\utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Development\SharewareZ\sharewarez\modules\utilities.py", line 129, in decorated_function
return f(*args, **kwargs)
       ^^^^^^^^^^^^^^^^^^
File "D:\Development\SharewareZ\sharewarez\modules\routes.py", line 1345, in game_edit
new_folder_size_bytes = get_folder_size_in_bytes(game.full_disk_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'get_folder_size_in_bytes' is not defined
```

Perhaps related to [commit](https://github.com/axewater/sharewarez/commit/6022c2bdbeee47f4881d36c78fb950c9decea5eb) for #27 ?

**Comment by axewater** [comment]
Sorry about that one ... indeed when I implemented support for filesizes in bytes I forgot to add an import statement. or my AI forgot.
